package com.example.entity;
// Generated Mar 7, 2018 10:38:38 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GradudeExam generated by hbm2java
 */
@Entity
@Table(name = "gradude_exam", catalog = "asm2")
public class GradudeExam implements java.io.Serializable {

	private Integer id;
	private Student student;
	private Test test;
	private double mark;
	private String notice;

	public GradudeExam() {
	}

	public GradudeExam(Student student, Test test, double mark, String notice) {
		this.student = student;
		this.test = test;
		this.mark = mark;
		this.notice = notice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "student", nullable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "test", nullable = false)
	public Test getTest() {
		return this.test;
	}

	public void setTest(Test test) {
		this.test = test;
	}

	@Column(name = "mark", nullable = false, precision = 22, scale = 0)
	public double getMark() {
		return this.mark;
	}

	public void setMark(double mark) {
		this.mark = mark;
	}

	@Column(name = "notice", nullable = false, length = 45)
	public String getNotice() {
		return this.notice;
	}

	public void setNotice(String notice) {
		this.notice = notice;
	}

}
