package com.example.entity;
// Generated Mar 7, 2018 10:38:38 AM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "asm2")
public class Student implements java.io.Serializable {

	private Integer id;
	private String name;
	private String address;
	private String birth;
	private Set<GradudeExam> gradudeExams = new HashSet<GradudeExam>(0);

	public Student() {
	}

	public Student(String name, String address, String birth) {
		this.name = name;
		this.address = address;
		this.birth = birth;
	}

	public Student(String name, String address, String birth, Set<GradudeExam> gradudeExams) {
		this.name = name;
		this.address = address;
		this.birth = birth;
		this.gradudeExams = gradudeExams;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", nullable = false, length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "birth", nullable = false, length = 45)
	public String getBirth() {
		return this.birth;
	}

	public void setBirth(String birth) {
		this.birth = birth;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	@JsonIgnore
	public Set<GradudeExam> getGradudeExams() {
		return this.gradudeExams;
	}

	public void setGradudeExams(Set<GradudeExam> gradudeExams) {
		this.gradudeExams = gradudeExams;
	}

}
