package com.example.entity;
// Generated Mar 7, 2018 10:38:38 AM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name = "test", catalog = "asm2")
public class Test implements java.io.Serializable {

	private Integer id;
	private String name;
	private String detail;
	private Set<GradudeExam> gradudeExams = new HashSet<GradudeExam>(0);

	public Test() {
	}

	public Test(String name, String detail) {
		this.name = name;
		this.detail = detail;
	}

	public Test(String name, String detail, Set<GradudeExam> gradudeExams) {
		this.name = name;
		this.detail = detail;
		this.gradudeExams = gradudeExams;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "detail", nullable = false, length = 45)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "test")
	@JsonIgnore
	public Set<GradudeExam> getGradudeExams() {
		return this.gradudeExams;
	}

	public void setGradudeExams(Set<GradudeExam> gradudeExams) {
		this.gradudeExams = gradudeExams;
	}

}
